### ISSUE TITLE
Error: The requested platform 'RFXCom' was not registered by any plugin.

### ISSUE THREAD

**Issue by Lorek162** [jhurliman/homebridge-rfxcom#11]
Hello, 

I'm having issue  installing this git, first thanks to jeanfabrice / homebridge-rfxcom for the updated dependencies 

I've installed this git but when i launch homebridge i get this error : 
```
[1/31/2019, 7:39:27 PM] Loaded config.json with 0 accessories and 1 platforms.
[1/31/2019, 7:39:27 PM] ---
[1/31/2019, 7:39:27 PM] No plugins found. See the README for information on installing plugins.
[1/31/2019, 7:39:27 PM] Loading 1 platforms...
/usr/lib/node_modules/homebridge/lib/api.js:122
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      ^

Error: The requested platform 'RFXCom' was not registered by any plugin.
    at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:122:13)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:316:45)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:86:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
```
Here's my config.json : 

```
{
  "bridge": {
    "name": "Homebridge",
    "username": "CC:22:3D:E3:CE:30",
    "port": 51826,
    "pin": "031-45-154"
  },

 "platforms": [
    {
      "platform": "RFXCom",
      "name": "RFXCom",
      "rfyRemotes": [
        {
          "name": "Awning",
          "deviceID": "0x000001/1",
          "openCloseSeconds": 18
        }
      ]
    }
  ]
}
```
I'm new to raspberry pi and homebridge and i'm lost with those error, does anyone have an idea ? 

Thanks

**Comment by Lorek162** [comment]
The git didn't installed itself correctly due to outdated dependency, it is working now
