### ISSUE TITLE
No RFY remotes configured

### ISSUE THREAD

**Issue by alexruperez** [jhurliman/homebridge-rfxcom#15]
Hi, I'm very close to getting it to work, but I'm getting this error.

```
[2019-12-1 21:54:17] [homebridge-rfxcom.RFXCom] WARN: No RFY remotes configured
[2019-12-1 21:54:17] TypeError: this.accessories.forEach is not a function
    at RFXComPlatform.removeAccessories (/usr/lib/node_modules/homebridge-rfxcom/index.js:233:20)
    at RFXComPlatform.didFinishLaunching (/usr/lib/node_modules/homebridge-rfxcom/index.js:87:10)
    at emitNone (events.js:111:20)
    at API.emit (events.js:208:7)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:103:13)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
```

My config.json is:
```
  "platforms": [
    {
      "platform": "RFXCom",
      "name": "RFXCom",
      "rfyRemotes": [
        {
          "name": "Awning",
          "deviceID": "0x020202/2",
          "openCloseSeconds": 30
        }
      ]
    }
  ]
```

I'm using RFXtrx433XL USB HA controller sync with RFXmngr in 0x020202/2.
Can someone help me please?

**Comment by jhurliman** [comment]
Are you still having this issue? Your configuration looks fine, but the error pasted above suggests `homebridge-rfxcom` is not seeing that configured platform. Are you sure your `config.json` is being picked up by Homebridge?

**Comment by glefand** [comment]
Hi,
I can help debug this if needed, but I cannot install the plugin due to dependencies issues.

**Comment by jhurliman** [comment]
#18 fixes the object.forEach crash for an empty configuration, keeps both rfyRemotes/rfyremotes spellings, and normalizes hexadecimal remote addresses before matching the transceiver list. A regression uses the 0x020202/2 address from this report. Successful listing and pairing still need verification on your actual RFXtrx433XL; no radio commands were sent during tests.
