### ISSUE TITLE
Installation problem on docker

### ISSUE THREAD

**Issue by Kydix** [jhurliman/homebridge-rfxcom#3]
Hi, 

i'm trying to install this pluging but i have a probleme with node serialport. The link is dead :( 

```
pi@raspberrypi:~/homebridge $ docker-compose exec homebridge npm install -g home                                                                                                                                                             bridge-rfxcom

> serialport@4.0.7 install /usr/local/lib/node_modules/homebridge-rfxcom/node_modules/serialport
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ '/usr/local/bin/node',
node-pre-gyp verb cli   '/usr/local/lib/node_modules/homebridge-rfxcom/node_modules/serialport/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.6.32
node-pre-gyp info using node@8.11.2 | linux | arm
node-pre-gyp verb command install []
node-pre-gyp info check checked for "/usr/local/lib/node_modules/homebridge-rfxcom/node_modules/serialport/build/Release/serialport.node" (not found)
node-pre-gyp http GET https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v57-linux-arm.tar.gz
node-pre-gyp http 404 https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v57-linux-arm.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v57-linux-arm.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for serialport@4.0.7 and node@8.11.2 (node-v57 ABI) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v57-linux-arm.tar.gz
node-pre-gyp verb command build [ 'rebuild' ]
make: Entering directory '/usr/local/lib/node_modules/homebridge-rfxcom/node_modules/serialport/build'
  CXX(target) Release/obj.target/serialport/src/serialport.o
../src/serialport.cpp: In function 'int getIntFromObject(v8::Local<v8::Object>, std::__cxx11::string)':
../src/serialport.cpp:90:52: warning: 'v8::Local<v8::Int32> v8::Value::ToInt32() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
   return getValueFromObject(options, key)->ToInt32()->Int32Value();
                                                    ^
In file included from /root/.node-gyp/8.11.2/include/node/node.h:63:0,
                 from ../../nan/nan.h:51,
                 from ../src/./serialport.h:7,
                 from ../src/serialport.cpp:1:
/root/.node-gyp/8.11.2/include/node/v8.h:9796:14: note: declared here
 Local<Int32> Value::ToInt32() const {
              ^~~~~
../src/serialport.cpp: In function 'double getDoubleFromObject(v8::Local<v8::Object>, std::__cxx11::string)':
../src/serialport.cpp:102:53: warning: 'v8::Local<v8::Number> v8::Value::ToNumber() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
   return getValueFromObject(options, key)->ToNumber()->NumberValue();
                                                     ^
In file included from /root/.node-gyp/8.11.2/include/node/node.h:63:0,
                 from ../../nan/nan.h:51,
                 from ../src/./serialport.h:7,
                 from ../src/serialport.cpp:1:
/root/.node-gyp/8.11.2/include/node/v8.h:9760:15: note: declared here
 Local<Number> Value::ToNumber() const {
               ^~~~~
../src/serialport.cpp: In function 'void EIO_AfterOpen(uv_work_t*)':
../src/serialport.cpp:174:31: warning: 'v8::Local<v8::Int32> v8::Value::ToInt32() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
     int fd = argv[1]->ToInt32()->Int32Value();
                               ^
In file included from /root/.node-gyp/8.11.2/include/node/node.h:63:0,
                 from ../../nan/nan.h:51,
                 from ../src/./serialport.h:7,
                 from ../src/serialport.cpp:1:
/root/.node-gyp/8.11.2/include/node/v8.h:9796:14: note: declared here
 Local<Int32> Value::ToInt32() const {
              ^~~~~
../src/serialport.cpp:180:30: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
   data->callback.Call(2, argv);
                              ^
In file included from ../src/./serialport.h:7:0,
                 from ../src/serialport.cpp:1:
../../nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/serialport.cpp: In function 'Nan::NAN_METHOD_RETURN_TYPE Update(Nan::NAN_METHOD_ARGS_TYPE)':
../src/serialport.cpp:193:29: warning: 'v8::Local<v8::Int32> v8::Value::ToInt32() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
   int fd = info[0]->ToInt32()->Int32Value();
                             ^
In file included from /root/.node-gyp/8.11.2/include/node/node.h:63:0,
                 from ../../nan/nan.h:51,
                 from ../src/./serialport.h:7,
                 from ../src/serialport.cpp:1:
/root/.node-gyp/8.11.2/include/node/v8.h:9796:14: note: declared here
 Local<Int32> Value::ToInt32() const {
              ^~~~~
../src/serialport.cpp:217:116: warning: 'v8::Local<v8::Int32> v8::Value::ToInt32() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
   baton->baudRate = Nan::Get(options, Nan::New<v8::String>("baudRate").ToLocalChecked()).ToLocalChecked()->ToInt32()->Int32Value();
                                                                                                                    ^
In file included from /root/.node-gyp/8.11.2/include/node/node.h:63:0,
                 from ../../nan/nan.h:51,
                 from ../src/./serialport.h:7,
                 from ../src/serialport.cpp:1:
/root/.node-gyp/8.11.2/include/node/v8.h:9796:14: note: declared here
 Local<Int32> Value::ToInt32() const {
              ^~~~~
../src/serialport.cpp: In function 'void EIO_AfterUpdate(uv_work_t*)':
../src/serialport.cpp:240:30: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
   data->callback.Call(1, argv);
                              ^
In file included from ../src/./serialport.h:7:0,
                 from ../src/serialport.cpp:1:
../../nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/serialport.cpp: In function 'Nan::NAN_METHOD_RETURN_TYPE Write(Nan::NAN_METHOD_ARGS_TYPE)':
../src/serialport.cpp:252:29: warning: 'v8::Local<v8::Int32> v8::Value::ToInt32() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
   int fd = info[0]->ToInt32()->Int32Value();
                             ^
In file included from /root/.node-gyp/8.11.2/include/node/node.h:63:0,
                 from ../../nan/nan.h:51,
                 from ../src/./serialport.h:7,
                 from ../src/serialport.cpp:1:
/root/.node-gyp/8.11.2/include/node/v8.h:9796:14: note: declared here
 Local<Int32> Value::ToInt32() const {
              ^~~~~
../src/serialport.cpp: In function 'void EIO_AfterWrite(uv_work_t*)':
../src/serialport.cpp:339:30: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
   data->callback.Call(1, argv);
                              ^
In file included from ../src/./serialport.h:7:0,
                 from ../src/serialport.cpp:1:
../../nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/serialport.cpp: In function 'Nan::NAN_METHOD_RETURN_TYPE Close(Nan::NAN_METHOD_ARGS_TYPE)':
../src/serialport.cpp:369:32: warning: 'v8::Local<v8::Int32> v8::Value::ToInt32() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
   baton->fd = info[0]->ToInt32()->Int32Value();
                                ^
In file included from /root/.node-gyp/8.11.2/include/node/node.h:63:0,
                 from ../../nan/nan.h:51,
                 from ../src/./serialport.h:7,
                 from ../src/serialport.cpp:1:
/root/.node-gyp/8.11.2/include/node/v8.h:9796:14: note: declared here
 Local<Int32> Value::ToInt32() const {
              ^~~~~
../src/serialport.cpp: In function 'void EIO_AfterClose(uv_work_t*)':
../src/serialport.cpp:403:30: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
   data->callback.Call(1, argv);
                              ^
In file included from ../src/./serialport.h:7:0,
                 from ../src/serialport.cpp:1:
../../nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/serialport.cpp: In function 'void EIO_AfterList(uv_work_t*)':
../src/serialport.cpp:465:30: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
   data->callback.Call(2, argv);
                              ^
In file included from ../src/./serialport.h:7:0,
                 from ../src/serialport.cpp:1:
../../nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/serialport.cpp: In function 'Nan::NAN_METHOD_RETURN_TYPE Flush(Nan::NAN_METHOD_ARGS_TYPE)':
../src/serialport.cpp:480:29: warning: 'v8::Local<v8::Int32> v8::Value::ToInt32() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
   int fd = info[0]->ToInt32()->Int32Value();
                             ^
In file included from /root/.node-gyp/8.11.2/include/node/node.h:63:0,
                 from ../../nan/nan.h:51,
                 from ../src/./serialport.h:7,
                 from ../src/serialport.cpp:1:
/root/.node-gyp/8.11.2/include/node/v8.h:9796:14: note: declared here
 Local<Int32> Value::ToInt32() const {
              ^~~~~
../src/serialport.cpp: In function 'void EIO_AfterFlush(uv_work_t*)':
../src/serialport.cpp:516:30: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
   data->callback.Call(2, argv);
                              ^
In file included from ../src/./serialport.h:7:0,
                 from ../src/serialport.cpp:1:
../../nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/serialport.cpp: In function 'Nan::NAN_METHOD_RETURN_TYPE Set(Nan::NAN_METHOD_ARGS_TYPE)':
../src/serialport.cpp:528:29: warning: 'v8::Local<v8::Int32> v8::Value::ToInt32() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
   int fd = info[0]->ToInt32()->Int32Value();
                             ^
In file included from /root/.node-gyp/8.11.2/include/node/node.h:63:0,
                 from ../../nan/nan.h:51,
                 from ../src/./serialport.h:7,
                 from ../src/serialport.cpp:1:
/root/.node-gyp/8.11.2/include/node/v8.h:9796:14: note: declared here
 Local<Int32> Value::ToInt32() const {
              ^~~~~
../src/serialport.cpp: In function 'void EIO_AfterSet(uv_work_t*)':
../src/serialport.cpp:573:30: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
   data->callback.Call(1, argv);
                              ^
In file included from ../src/./serialport.h:7:0,
                 from ../src/serialport.cpp:1:
../../nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/serialport.cpp: In function 'Nan::NAN_METHOD_RETURN_TYPE Drain(Nan::NAN_METHOD_ARGS_TYPE)':
../src/serialport.cpp:585:29: warning: 'v8::Local<v8::Int32> v8::Value::ToInt32() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
   int fd = info[0]->ToInt32()->Int32Value();
                             ^
In file included from /root/.node-gyp/8.11.2/include/node/node.h:63:0,
                 from ../../nan/nan.h:51,
                 from ../src/./serialport.h:7,
                 from ../src/serialport.cpp:1:
/root/.node-gyp/8.11.2/include/node/v8.h:9796:14: note: declared here
 Local<Int32> Value::ToInt32() const {
              ^~~~~
../src/serialport.cpp: In function 'void EIO_AfterDrain(uv_work_t*)':
../src/serialport.cpp:617:30: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
   data->callback.Call(1, argv);
                              ^
In file included from ../src/./serialport.h:7:0,
                 from ../src/serialport.cpp:1:
../../nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
  CXX(target) Release/obj.target/serialport/src/serialport_unix.o
../src/serialport_unix.cpp:32:26: fatal error: linux/serial.h: No such file or directory

                          ^
compilation terminated.
make: *** [serialport.target.mk:95: Release/obj.target/serialport/src/serialport_unix.o] Error 1
make: Leaving directory '/usr/local/lib/node_modules/homebridge-rfxcom/node_modules/serialport/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.9.80-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/local/lib/node_modules/homebridge-rfxcom/node_modules/serialport/build/Release/serialport.node" "--module_name=serialport" "--module_path=/usr/local/lib/node_modules/homebridge-rfxcom/node_modules/serialport/build/Release"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-rfxcom/node_modules/serialport
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/homebridge-rfxcom/node_modules/serialport/build/Release/serialport.node --module_name=serialport --module_path=/usr/local/lib/node_modules/homebridge-rfxcom/node_modules/serialport/build/Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/homebridge-rfxcom/node_modules/serialport/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 4.9.80-v7+
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/homebridge-rfxcom/node_modules/serialport/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/homebridge-rfxcom/node_modules/serialport
node-pre-gyp ERR! node -v v8.11.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.32
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/homebridge-rfxcom/node_modules/serialport/build/Release/serialport.node --module_name=serialport --module_path=/usr/local/lib/node_modules/homebridge-rfxcom/node_modules/serialport/build/Release' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! serialport@4.0.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the serialport@4.0.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-06-08T18_25_08_059Z-debug.log
```

**Comment by Kydix** [comment]
I reinstalled homebridge via another method and it's OK. You can close
