### ISSUE TITLE
can't install (homebridge running on MacOS)

### ISSUE THREAD

**Issue by ghost** [jhurliman/homebridge-rfxcom#9]
Hi

Got my RFXcom transceiver today, programmed it through the Windows tool to my Somfy RTS garage door (works fine), but I can't seem to install your rfxcom package on my homebridge server (running on a MacOS 10.14 platform). It fails at the serialport package installation.
Here's the log for it : any ideas?

sudo npm install -g homebridge-rfxcom
Password:

> serialport@4.0.7 install /usr/local/lib/node_modules/homebridge-rfxcom/node_modules/serialport
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ '/usr/local/bin/node',
node-pre-gyp verb cli   '/usr/local/lib/node_modules/homebridge-rfxcom/node_modules/serialport/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.6.32
node-pre-gyp info using node@10.13.0 | darwin | x64
node-pre-gyp verb command install []
node-pre-gyp info check checked for "/usr/local/lib/node_modules/homebridge-rfxcom/node_modules/serialport/build/Release/serialport.node" (not found)
node-pre-gyp http GET https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(undefined): https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for serialport@4.0.7 and node@10.13.0 (node-v64 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http EACCES: permission denied, mkdir '/usr/local/lib/node_modules/homebridge-rfxcom/node_modules/serialport/build' 
node-pre-gyp verb command build [ 'rebuild' ]
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/homebridge-rfxcom/node_modules/serialport/build'
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/local/lib/node_modules/homebridge-rfxcom/node_modules/serialport/build/Release/serialport.node" "--module_name=serialport" "--module_path=/usr/local/lib/node_modules/homebridge-rfxcom/node_modules/serialport/build/Release"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-rfxcom/node_modules/serialport
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/homebridge-rfxcom/node_modules/serialport/build/Release/serialport.node --module_name=serialport --module_path=/usr/local/lib/node_modules/homebridge-rfxcom/node_modules/serialport/build/Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/homebridge-rfxcom/node_modules/serialport/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Darwin 18.2.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/homebridge-rfxcom/node_modules/serialport/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/homebridge-rfxcom/node_modules/serialport
node-pre-gyp ERR! node -v v10.13.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.32
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/homebridge-rfxcom/node_modules/serialport/build/Release/serialport.node --module_name=serialport --module_path=/usr/local/lib/node_modules/homebridge-rfxcom/node_modules/serialport/build/Release' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! serialport@4.0.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serialport@4.0.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by ghost** [comment]
ok, figured it on my own, issue can be closed, got it to work perfectly. For those having a similar issue, you need to setup dependencies (serialport and rfxcom) through npm, and then get the files for homebridge-rfxcom from this git and copy them manually to your homebridge folder. Also, make sure to remove your homebridge setup from the Home iOS app if it was already present, and set it up again, otherwise you might just like me end up with a homebridge not responding status on the Home app...
